name: Build and Format

on:
  push:
    branches:
      - main  # change to your main branch name
  pull_request:
    branches:
      - main  # change to your main branch name

jobs:
  build_and_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy python3 python3-pip
          python3 -m pip install cmake-format

      - name: Build and test with CMake
        run: |
          cmake -B build -S . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          cmake --build build

      - name: Run clang-tidy
        run: |
          clang-tidy -p src/*.c

      - name: Format C source files
        run: |
          find src/ -name '*.c' -exec clang-format -i -style=Google -QualifierAlignment=Left {} \;

      - name: Format CMake source files
        run: |
          find src/ -name 'CMakeLists.txt' -exec cmake-format -i {} \;
